FROM registry.access.redhat.com/ubi9/openjdk-21:1.21

ENV LANGUAGE='en_US:en'

# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --chown=185 target/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 target/quarkus-app/*.jar /deployments/
COPY --chown=185 target/quarkus-app/app/ /deployments/app/
COPY --chown=185 target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185

ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager" \
    JAVA_APP_JAR="/deployments/quarkus-run.jar" \
    JAVA_OPTS="\
  -server \
  -XX:+UnlockExperimentalVMOptions \
  -XX:+UseZGC \
  -XX:+AlwaysPreTouch \
  -XX:+EnableJVMCI \
  -Dquarkus.vertx.prefer-native-transport=true \
  -Dio.netty.buffer.checkBounds=false \
  -Dio.netty.tryReflectionSetAccessible=true \
  -Dio.netty.allocator.type=pooled \
  -Dio.netty.allocator.cacheTrimInterval=600000 \
  -Dmutiny.disableCallBackDecorators=true \
  -Dvertx.disableHttpHeadersValidation=true \
  -Dvertx.disableWebsockets=true \
  -Dvertx.disableTCCL=true \
  -XX:+ExitOnOutOfMemoryError \
  -XX:InitialRAMPercentage=70 \
  -XX:MinRAMPercentage=70 \
  -XX:MaxRAMPercentage=85 \
  -Xss256k \
  -XX:MetaspaceSize=32M \
  -XX:MaxMetaspaceSize=64M \
  -XX:+UseTransparentHugePages \
  -XX:+UseCompressedOops \
  -XX:+UseCompressedClassPointers \
  -XX:+TieredCompilation \
  -XX:TieredStopAtLevel=1 \
  -Djava.security.egd=file:/dev/./urandom"

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]

