quarkus.swagger-ui.always-include=true

# Para melhor performance com operações reativas
quarkus.redis.hosts=${QUARKUS_REDIS_HOST:redis://localhost:6379}
# quarkus.redis.max-pool-size=50
# quarkus.redis.max-pool-waiting=100

# Redis optimizations for native
quarkus.redis.timeout=5s
quarkus.redis.max-pool-size=50
quarkus.redis.max-pool-waiting=25

# quarkus.redis.pool-recycle-timeout=15s
# quarkus.redis.pool-cleaner-interval=30s
# quarkus.redis.timeout=10s


# Configurações de reconexão
quarkus.redis.reconnect-attempts=3


# Payment Service Configuration - High Performance
# payment.default.url=${PAYMENT_PROCESSOR_DEFAULT:http://localhost:8001}
# payment.fallback.url=${PAYMENT_PROCESSOR_FALLBACK:http://localhost:8002}

# payment.connect.timeout.millis=2000


quarkus.log.console.enable=true
quarkus.log.file.enable=false


# Habilita transporte nativo do Netty (melhora latência em Linux)
quarkus.vertx.prefer-native-transport=true


# Otimizações de pool de threads
quarkus.thread-pool.core-threads=16
# quarkus.thread-pool.max-threads=64

# Logging mais enxuto por padrão
# quarkus.log.level=WARN
# quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n

# NETTY / Mutiny
# quarkus.log.level=WARN
# quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n


# application.properties otimizado para Native
quarkus.native.container-build=true
# quarkus.native.additional-build-args=\
#   --initialize-at-run-time=io.netty.handler.ssl.OpenSsl,\
#   --initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslEngine,\
#   --initialize-at-run-time=io.netty.internal.tcnative.SSL,\
#   --initialize-at-run-time=io.netty.internal.tcnative.Library,\
#   --initialize-at-run-time=io.netty.internal.tcnative.CertificateRequestedCallback,\
#   --initialize-at-run-time=io.netty.internal.tcnative.CertificateVerifier,\
#   --initialize-at-run-time=io.netty.internal.tcnative.SessionTicketKeyCallback,\
#   --enable-url-protocols=http,\
#   --enable-all-security-services,\
#   -H:+StaticExecutableWithDynamicLibC,\
#   -H:+ReportExceptionStackTraces,\
#   -H:IncludeResources=.*\\.properties\$

# Thread configuration for native
quarkus.thread-pool.core-threads=4
quarkus.thread-pool.max-threads=16
quarkus.thread-pool.queue-size=100

# HTTP configuration optimized for native
quarkus.http.io-threads=4
quarkus.http.worker-threads=8
quarkus.http.so-reuse-port=true

quarkus.ssl.native=false
quarkus.native.enable-https-url-handler=false
